name: arch.x86_64.asan
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: ci-test-asan
        uses: falconindy/arch-dockerbuild@v1
        with:
          entrypoint: 'build-aux/ci-test-asan'
